name: hitchspots
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cloud_firestore: ^2.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.3
  firebase_analytics: ^8.1.2
  firebase_auth: ^1.2.0
  firebase_crashlytics: ^2.0.6
  firebase_storage: ^8.1.1
  flutter_dotenv: 4.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  geocoding: ^2.0.0
  geoflutterfire2: ^2.3.5
  google_maps_cluster_manager: ^1.0.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.4
  http: ^0.13.3
  location: ^4.1.1
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.2
  permission_handler: ^8.0.1
  provider: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/locations/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"
  adaptive_icon_background: "#06D6A0"
  adaptive_icon_foreground: "assets/adaptive_foreground.png"
